"""empty message

Revision ID: 5c8b99f6be7a
Revises: ae593d942349
Create Date: 2020-09-06 00:24:01.729826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8b99f6be7a'
down_revision = 'ae593d942349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actor_movie_id_fkey', 'actor', type_='foreignkey')
    op.drop_column('actor', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('actor_movie_id_fkey', 'actor', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
